# Generated by Django 2.1.2 on 2018-11-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=20)),
                ('respuesta', models.CharField(max_length=150)),
            ],
        ),
    ]
